import React from "react";
import {createRoot} from "react-dom/client";
import {ArrowUpRight, Github, Mail, ExternalLink, Sparkles, MapPin} from "lucide-react";
import "./styles.css";

const projects=[
 {n:"01",title:"CareerViQ",tag:"Career Guidance Platform",desc:"Career guidance platform with resources, blogs and a responsive learning-focused experience.",stack:["Angular","Django REST","PostgreSQL","JWT"],url:"https://careerviq.com",tone:"from-violet-500/25"},
 {n:"02",title:"GP Torsole",tag:"Government Web Portal",desc:"Gram Panchayat portal for village information, notices, schemes and citizen services.",stack:["Angular","Django","REST API","VPS"],url:"https://gptorsole.in",tone:"from-emerald-400/20"},
 {n:"03",title:"GP Valivande",tag:"Government Web Portal",desc:"Public portal for village information, government schemes, notices and digital citizen services.",stack:["Angular","Django","PostgreSQL","Tailwind"],url:"https://gpvalivande.in",tone:"from-orange-400/20"}
];
const skills=[
 ["Programming","Python · Java · JavaScript · TypeScript · SQL · HTML5 · CSS3"],
 ["Frontend","Angular · Tailwind CSS · Bootstrap"],
 ["Backend","Django · DRF · REST APIs · JWT · LangChain"],
 ["Data","PostgreSQL · Microsoft SQL Server · SQLite"],
 ["Tools","Git · GitHub · Docker · Postman · Google Colab · VS Code"],
 ["Deployment","Hostinger VPS · Production web deployment"]
];

function App(){
 const go=id=>document.getElementById(id)?.scrollIntoView({behavior:"smooth"});
 return <div className="min-h-screen bg-[#070707] text-white overflow-x-hidden">
  <div className="fixed inset-0 -z-10 pointer-events-none"><div className="absolute -left-32 -top-32 w-[40rem] h-[40rem] rounded-full bg-violet-500/10 blur-[120px]"/><div className="absolute -right-32 top-1/3 w-[34rem] h-[34rem] rounded-full bg-cyan-400/5 blur-[130px]"/><div className="noise absolute inset-0 opacity-[.035]"/></div>
  <header className="sticky top-0 z-50 border-b border-white/10 bg-[#070707]/75 backdrop-blur-xl"><nav className="max-w-6xl mx-auto px-5 lg:px-8 py-4 flex items-center justify-between"><button onClick={()=>go("home")} className="font-display font-bold">PG<span className="text-white/30">.</span></button><div className="hidden md:flex gap-8 text-sm text-white/50">{["work","about","contact"].map(x=><button key={x} onClick={()=>go(x)} className="capitalize hover:text-white">{x}</button>)}</div><a href="mailto:pratikgaonkar577@gmail.com" className="rounded-full border border-white/10 bg-white/5 px-4 py-2 text-xs hover:bg-white/10">Let's talk</a></nav></header>
  <main id="home">
   <section className="max-w-6xl mx-auto min-h-[calc(100vh-65px)] px-5 lg:px-8 py-20 grid lg:grid-cols-[1.15fr_.85fr] gap-14 items-center">
    <div><div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.03] px-3 py-1.5 text-[11px] uppercase tracking-[.18em] text-white/50 mb-7"><span className="w-1.5 h-1.5 rounded-full bg-emerald-400"/>Available for opportunities</div><p className="text-sm text-white/40 mb-5">Pratik Bharat Gaonkar</p><h1 className="font-display text-5xl sm:text-6xl lg:text-8xl font-semibold leading-[.98] tracking-[-.055em]">Building useful<span className="block text-white/35">digital products.</span></h1><p className="mt-7 max-w-2xl text-base sm:text-lg leading-7 text-white/50">B.E. Artificial Intelligence & Machine Learning student focused on full-stack web development, practical AI, and thoughtful interfaces.</p><div className="mt-9 flex flex-wrap gap-3"><button onClick={()=>go("work")} className="inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-semibold text-black hover:-translate-y-0.5">View selected work <ArrowUpRight size={16}/></button><a href="https://github.com/PROGHEIST" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full border border-white/10 px-5 py-3 text-sm text-white/70 hover:bg-white/5"><Github size={16}/>GitHub</a></div><div className="mt-12 flex gap-2 items-center text-xs text-white/35"><MapPin size={14}/>Thane, Maharashtra · India</div></div>
    <div className="max-w-[420px] w-full mx-auto"><div className="aspect-[4/5] rounded-[2rem] border border-white/10 bg-gradient-to-br from-white/10 via-white/[.03] to-violet-500/10 p-1 shadow-glow"><div className="h-full rounded-[1.7rem] bg-[#0c0c0c] p-7 flex flex-col justify-between"><div className="flex justify-between text-xs text-white/30"><span>PORTFOLIO / 2026</span><Sparkles size={14}/></div><div><div className="w-16 h-16 rounded-2xl border border-white/10 bg-white/5 p-4 mb-5"><div className="h-full flex items-end gap-1"><i className="w-2 h-1/2 bg-white/30 rounded"/><i className="w-2 h-4/5 bg-white/50 rounded"/><i className="w-2 h-full bg-white/80 rounded"/></div></div><p className="font-display text-3xl font-semibold">AI × Web</p><p className="mt-2 text-sm text-white/40 leading-6 max-w-[250px]">From APIs and data to interfaces that feel simple.</p></div><div className="grid grid-cols-2 gap-3 text-[11px] text-white/40"><div className="rounded-xl border border-white/10 p-3"><b className="block text-white/70">2027</b>Graduation</div><div className="rounded-xl border border-white/10 p-3"><b className="block text-white/70">3+</b>Live projects</div></div></div></div></div>
   </section>
   <section id="work" className="scroll-mt-20 border-t border-white/10"><div className="max-w-6xl mx-auto px-5 lg:px-8 py-24"><div className="mb-12 flex flex-col md:flex-row md:items-end justify-between gap-5"><div><p className="text-xs uppercase tracking-[.18em] text-white/30 mb-3">Selected work</p><h2 className="font-display text-4xl sm:text-5xl font-semibold tracking-[-.04em]">Projects with purpose.</h2></div><p className="max-w-sm text-sm leading-6 text-white/40">Career-tech and civic digital experiences, built and deployed end-to-end.</p></div><div className="space-y-5">{projects.map(p=><article key={p.title} className="overflow-hidden rounded-[1.75rem] border border-white/10 bg-white/[.025] hover:border-white/20"><div className={"grid lg:grid-cols-[.22fr_1fr_.22fr] gap-8 min-h-[300px] p-7 sm:p-10 bg-gradient-to-br "+p.tone+" via-white/[.01] to-transparent"}><div className="flex justify-between lg:block"><span className="font-display text-sm text-white/20">{p.n}</span><span className="lg:block lg:mt-12 rounded-full border border-white/10 px-3 py-1 text-[10px] uppercase tracking-[.16em] text-white/40 w-fit">{p.tag}</span></div><div className="flex flex-col justify-center"><h3 className="font-display text-4xl sm:text-5xl font-semibold tracking-[-.045em]">{p.title}</h3><p className="mt-4 max-w-xl text-white/45 leading-6">{p.desc}</p><div className="mt-7 flex flex-wrap gap-2">{p.stack.map(s=><span key={s} className="rounded-full border border-white/10 bg-black/20 px-2.5 py-1 text-[11px] text-white/40">{s}</span>)}</div></div><div className="flex items-end lg:justify-end"><a href={p.url} target="_blank" rel="noreferrer" className="inline-flex gap-2 items-center text-sm text-white/55 hover:text-white">Visit site <ExternalLink size={15}/></a></div></div></article>)}</div></div></section>
   <section id="about" className="scroll-mt-20 border-t border-white/10"><div className="max-w-6xl mx-auto px-5 lg:px-8 py-24 grid lg:grid-cols-[.8fr_1.2fr] gap-14"><div><p className="text-xs uppercase tracking-[.18em] text-white/30 mb-3">About</p><h2 className="font-display text-4xl sm:text-5xl font-semibold tracking-[-.04em]">Curious by default. Practical by design.</h2></div><div><p className="text-lg leading-8 text-white/50">I'm a Computer Engineering graduate pursuing a B.E. in Artificial Intelligence & Machine Learning. I enjoy taking ideas from a rough concept to a working product — designing the interface, shaping the API, connecting the database, and getting it live.</p><div className="mt-10 grid sm:grid-cols-2 gap-3">{skills.map(([a,b])=><div key={a} className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><p className="text-[11px] uppercase tracking-[.16em] text-white/30">{a}</p><p className="mt-3 text-sm leading-6 text-white/55">{b}</p></div>)}</div><div className="mt-6 grid sm:grid-cols-2 gap-3"><div className="rounded-2xl border border-white/10 p-5"><p className="text-[11px] uppercase tracking-[.16em] text-white/30">Education</p><p className="mt-3 text-sm text-white/70">B.E. Artificial Intelligence & Machine Learning</p><p className="mt-1 text-xs text-white/35">2024 — 2027 · Shivajirao S. Jondhale College of Engineering</p></div><div className="rounded-2xl border border-white/10 p-5"><p className="text-[11px] uppercase tracking-[.16em] text-white/30">Certification</p><p className="mt-3 text-sm text-white/70">Full Stack Development</p><p className="mt-1 text-xs text-white/35">Udemy · Angular + Django + DRF</p></div></div></div></div></section>
   <section id="contact" className="scroll-mt-20 border-t border-white/10"><div className="max-w-6xl mx-auto px-5 lg:px-8 py-24"><div className="rounded-[2rem] border border-white/10 bg-gradient-to-br from-white/[.07] to-white/[.015] p-7 sm:p-12"><p className="text-xs uppercase tracking-[.18em] text-white/30 mb-3">Contact</p><div className="grid lg:grid-cols-[1fr_auto] gap-10 lg:items-end"><div><h2 className="font-display text-4xl sm:text-6xl font-semibold tracking-[-.05em] max-w-3xl">Have a product, problem, or idea?</h2><p className="mt-5 text-white/40">Let's turn it into something people can actually use.</p></div><a href="mailto:pratikgaonkar577@gmail.com" className="inline-flex w-fit items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-semibold text-black"><Mail size={16}/>pratikgaonkar577@gmail.com</a></div><div className="mt-12 pt-7 border-t border-white/10"><a href="https://github.com/PROGHEIST" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-sm text-white/50 hover:text-white"><Github size={16}/>GitHub</a></div></div></div></section>
  </main>
  <footer className="border-t border-white/10"><div className="max-w-6xl mx-auto px-5 lg:px-8 py-7 flex justify-between text-xs text-white/30"><span>© 2026 Pratik Bharat Gaonkar</span><span>Designed & built with React.</span></div></footer>
 </div>
}
createRoot(document.getElementById("root")).render(<App/>);
